'use client';

import * as React from 'react';
import { useAuthStore } from '@/store/use-auth-store';
import { paymentService } from '@/services/payment.service';
import { loadRazorpay } from '@/utils/razorpay-loader';
import { useRouter } from 'next/navigation';
import { Section } from '@/components/ui/section';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { motion } from 'framer-motion';
import { 
  Zap, 
  Layers, 
  Check, 
  ShieldCheck, 
  HelpCircle, 
  Sparkles, 
  Infinity as InfinityIcon, 
  Star,
  Map,
  Compass,
  ArrowRight,
  Loader2,
  Lock,
  RefreshCw
} from 'lucide-react';

export default function CheckoutPage() {
  const { user, checkAuth } = useAuthStore();
  const router = useRouter();
  const [loadingProduct, setLoadingProduct] = React.useState<string | null>(null);

  const handleCheckout = async (productType: 'SLOT' | 'PRO') => {
    setLoadingProduct(productType);
    const productName = productType === 'SLOT' ? 'Extra Itinerary Slot' : 'Lifetime PRO Nomad';
    
    try {
      // Step 1: Load Razorpay SDK
      const sdkLoaded = await loadRazorpay();
      if (!sdkLoaded) {
        toast.error('Razorpay SDK failed to load. Are you online?', {
          description: 'Please check your connection and try again.'
        });
        setLoadingProduct(null);
        return;
      }

      // Step 2: Create Order in Backend
      let orderData;
      if (productType === 'SLOT') {
        orderData = await paymentService.createSlotOrder();
      } else {
        orderData = await paymentService.createPlanOrder();
      }

      if (!orderData || !orderData.orderId) {
        throw new Error('Invalid order metadata generated by backend.');
      }

      // Step 3: Trigger Razorpay PopUp
      const options = {
        key: orderData.key || process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID || 'rzp_test_fLjLz0BJbniTcg',
        amount: orderData.amount,
        currency: orderData.currency,
        name: 'Travenic',
        description: productName,
        order_id: orderData.orderId,
        handler: async function (response: any) {
          try {
            setLoadingProduct(productType);
            toast.loading('Verifying your payment signature...', { id: 'payment-verify' });
            
            const verifyData = {
              razorpay_order_id: response.razorpay_order_id,
              razorpay_payment_id: response.razorpay_payment_id,
              razorpay_signature: response.razorpay_signature
            };
            
            await paymentService.verifyPayment(verifyData);
            
            // Instantly sync user auth status
            await checkAuth();
            
            toast.success('Payment Verified! Account upgraded successfully.', { id: 'payment-verify' });
            
            // Redirect to dedicated success outcome
            router.push(`/dashboard/checkout/success?orderId=${orderData.orderId}&paymentId=${response.razorpay_payment_id}&product=${encodeURIComponent(productName)}&amount=${orderData.amount / 100}`);
          } catch (err: any) {
            toast.error('Signature verification failed.', { id: 'payment-verify' });
            router.push(`/dashboard/checkout/failure?error=${encodeURIComponent(err.message || 'Payment verification failed.')}&product=${encodeURIComponent(productName)}`);
          } finally {
            setLoadingProduct(null);
          }
        },
        prefill: {
          name: user?.name || '',
          email: user?.email || '',
          contact: (user as any)?.phone || ''
        },
        theme: {
          color: '#0ea5e9' // beautiful sky-500 theme
        },
        modal: {
          ondismiss: function() {
            setLoadingProduct(null);
            toast.info('Checkout cancelled.');
            router.push(`/dashboard/checkout/failure?error=User closed the payment portal&product=${encodeURIComponent(productName)}`);
          }
        }
      };

      const paymentObject = new (window as any).Razorpay(options);
      paymentObject.open();
    } catch (error: any) {
      toast.error('Payment Initialization Failed', {
        description: error.response?.data?.error || error.message || 'Could not communicate with payment gateways.'
      });
      setLoadingProduct(null);
    }
  };

  const slotFeatures = [
    'Adds +1 permanent active itinerary',
    'Custom smart AI routes and suggestions',
    'Full interactive transport details',
    'Lifetime persistence of trip records',
    'Offline PDF itinerary exports',
  ];

  const proFeatures = [
    'UNLIMITED active itineraries',
    'UNLIMITED AI smart generation iterations',
    'Early access to backpacker travel circuits',
    'Priority VIP 24/7 customer support',
    'Advanced offline maps configuration',
    'Pre-loaded seed data & premium spots details',
  ];

  return (
    <Section className="py-12 max-w-7xl mx-auto px-4 md:px-8">
      {/* Header and Title */}
      <div className="mb-16 text-center md:text-left relative">
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <div className="inline-flex items-center gap-2 mb-4 bg-sky-500/10 text-sky-500 px-3 py-1.5 rounded-full border border-sky-500/20">
            <ShieldCheck className="h-4 w-4" />
            <span className="text-[10px] font-black uppercase tracking-[0.2em]">Secure Checkout Gateway</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-black font-heading tracking-tighter italic text-slate-900 mb-4">
            Travenic <span className="text-sky-500">Premium.</span>
          </h1>
          <p className="text-slate-500 font-medium text-base max-w-2xl">
            Upgrade your travel engineering toolkit. Select from slot extensions or lifetime membership to unleash unrestricted travel exploration.
          </p>
        </motion.div>
      </div>

      {/* Product Offers Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
        
        {/* Slot Card */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          <Card className="h-full border-none bg-white rounded-[2.5rem] shadow-xl hover:shadow-2xl transition-all duration-300 flex flex-col overflow-hidden group">
            <CardHeader className="p-8 pb-4 relative">
              <div className="h-12 w-12 rounded-2xl bg-indigo-50 flex items-center justify-center text-indigo-500 mb-6 group-hover:scale-110 transition-transform">
                <Layers className="h-6 w-6" />
              </div>
              <Badge className="w-fit bg-indigo-50 hover:bg-indigo-100 text-indigo-600 border-none font-black px-3 py-1 rounded-md mb-3 text-[9px] tracking-widest uppercase">
                Slot Addon
              </Badge>
              <CardTitle className="text-2xl font-black font-heading text-slate-900 mb-2">
                Extra Itinerary Slot
              </CardTitle>
              <CardDescription className="text-slate-400 font-medium text-sm">
                Unlock an additional slot for active trips. Best for travelers handling parallel itineraries.
              </CardDescription>
            </CardHeader>

            <CardContent className="p-8 pt-0 flex-1">
              <div className="my-6 py-4 bg-slate-50 rounded-2xl px-6 border border-slate-100">
                <span className="text-slate-400 text-[10px] font-black uppercase tracking-widest block mb-1">One-time payment</span>
                <div className="flex items-baseline gap-1">
                  <span className="text-4xl font-black text-slate-900">₹199</span>
                  <span className="text-slate-400 font-bold text-xs uppercase tracking-widest">/ Slot</span>
                </div>
              </div>

              <div className="space-y-4">
                <p className="text-slate-500 font-black text-[10px] uppercase tracking-widest mb-2">What is unlocked:</p>
                {slotFeatures.map((feat) => (
                  <div key={feat} className="flex items-start gap-3">
                    <div className="h-5 w-5 rounded-full bg-indigo-50 flex items-center justify-center shrink-0 mt-0.5">
                      <Check className="h-3 w-3 text-indigo-600" />
                    </div>
                    <span className="text-sm font-semibold text-slate-600 leading-tight">{feat}</span>
                  </div>
                ))}
              </div>
            </CardContent>

            <CardFooter className="p-8 pt-0 mt-auto">
              <Button
                onClick={() => handleCheckout('SLOT')}
                disabled={loadingProduct !== null}
                className="w-full h-14 rounded-2xl bg-slate-900 hover:bg-indigo-600 text-white font-black text-xs uppercase tracking-[0.2em] transition-all group shadow-lg shadow-slate-900/10"
              >
                {loadingProduct === 'SLOT' ? (
                  <span className="flex items-center gap-2">
                    <Loader2 className="h-4 w-4 animate-spin text-white" />
                    Opening Razorpay Gateway...
                  </span>
                ) : (
                  <span className="flex items-center justify-center gap-2">
                    Buy Extra Slot
                    <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
                  </span>
                )}
              </Button>
            </CardFooter>
          </Card>
        </motion.div>

        {/* Lifetime PRO Card */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <Card className="h-full border-2 border-amber-400/50 bg-slate-950 text-white rounded-[2.5rem] shadow-2xl hover:shadow-3xl transition-all duration-300 flex flex-col overflow-hidden relative group">
            
            {/* Ambient Background Gradient Glow */}
            <div className="absolute top-0 right-0 h-40 w-40 bg-sky-500/10 rounded-full blur-[80px] pointer-events-none" />
            <div className="absolute bottom-0 left-0 h-40 w-40 bg-amber-500/10 rounded-full blur-[80px] pointer-events-none" />

            <div className="absolute top-6 right-6">
              <Badge className="bg-gradient-to-r from-amber-400 to-orange-500 hover:scale-105 text-white border-none font-black px-3.5 py-1.5 rounded-lg text-[9px] tracking-widest uppercase shadow-lg shadow-amber-500/20">
                ⭐ BEST VALUE
              </Badge>
            </div>

            <CardHeader className="p-8 pb-4 relative">
              <div className="h-12 w-12 rounded-2xl bg-amber-500/10 flex items-center justify-center text-amber-400 mb-6 group-hover:scale-110 transition-transform">
                <Zap className="h-6 w-6 fill-amber-400" />
              </div>
              <Badge className="w-fit bg-amber-400/20 text-amber-300 border-none font-black px-3 py-1 rounded-md mb-3 text-[9px] tracking-widest uppercase">
                Pro Upgrade
              </Badge>
              <CardTitle className="text-2xl font-black font-heading text-white mb-2">
                Lifetime PRO Nomad
              </CardTitle>
              <CardDescription className="text-slate-400 font-medium text-sm">
                Unrestricted infinite itineraries, boundless smart generation tools, and lifetime system updates.
              </CardDescription>
            </CardHeader>

            <CardContent className="p-8 pt-0 flex-1">
              <div className="my-6 py-4 bg-white/5 rounded-2xl px-6 border border-white/5">
                <span className="text-slate-400 text-[10px] font-black uppercase tracking-widest block mb-1">Lifetime Unlimited Access</span>
                <div className="flex items-baseline gap-1">
                  <span className="text-4xl font-black text-white">₹999</span>
                  <span className="text-amber-400 font-black text-xs uppercase tracking-widest">/ Infinite</span>
                </div>
              </div>

              <div className="space-y-4">
                <p className="text-slate-400 font-black text-[10px] uppercase tracking-widest mb-2">What is unlocked:</p>
                {proFeatures.map((feat) => (
                  <div key={feat} className="flex items-start gap-3">
                    <div className="h-5 w-5 rounded-full bg-white/10 flex items-center justify-center shrink-0 mt-0.5">
                      <Check className="h-3 w-3 text-amber-400" />
                    </div>
                    <span className="text-sm font-semibold text-slate-300 leading-tight">{feat}</span>
                  </div>
                ))}
              </div>
            </CardContent>

            <CardFooter className="p-8 pt-0 mt-auto">
              <Button
                onClick={() => handleCheckout('PRO')}
                disabled={loadingProduct !== null}
                className="w-full h-14 rounded-2xl bg-gradient-to-r from-amber-400 to-orange-500 hover:from-amber-500 hover:to-orange-600 text-slate-950 font-black text-xs uppercase tracking-[0.2em] transition-all group shadow-xl shadow-amber-500/20"
              >
                {loadingProduct === 'PRO' ? (
                  <span className="flex items-center gap-2 justify-center text-slate-900">
                    <Loader2 className="h-4 w-4 animate-spin text-slate-900" />
                    Connecting Secure Terminal...
                  </span>
                ) : (
                  <span className="flex items-center justify-center gap-2">
                    Claim Lifetime Access
                    <Zap className="h-4 w-4 fill-slate-950 text-slate-950 group-hover:scale-125 transition-transform" />
                  </span>
                )}
              </Button>
            </CardFooter>
          </Card>
        </motion.div>
      </div>

      {/* Features Detail Comparison Grid Matrix */}
      <div className="mb-20">
        <div className="text-center mb-10">
          <h2 className="text-2xl font-black font-heading text-slate-900 mb-2">Membership Matrix</h2>
          <p className="text-slate-400 font-bold uppercase text-[10px] tracking-widest">Compare our system configurations</p>
        </div>

        <div className="bg-white rounded-[2rem] border border-slate-100 overflow-hidden shadow-xl">
          <table className="w-full border-collapse text-left">
            <thead>
              <tr className="border-b border-slate-100 bg-slate-50/50">
                <th className="p-6 text-sm font-black uppercase tracking-widest text-slate-400">Features</th>
                <th className="p-6 text-sm font-black uppercase tracking-widest text-slate-400 text-center">Free Roam</th>
                <th className="p-6 text-sm font-black uppercase tracking-widest text-slate-400 text-center">Extra Slots</th>
                <th className="p-6 text-sm font-black uppercase tracking-widest text-amber-500 text-center bg-amber-500/5">PRO Nomad</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-slate-100/50 hover:bg-slate-50/20 transition-colors">
                <td className="p-6 text-sm font-bold text-slate-800">Active Itinerary Slots</td>
                <td className="p-6 text-sm font-semibold text-slate-500 text-center">1 Active Limit</td>
                <td className="p-6 text-sm font-semibold text-indigo-600 text-center">+1 Per Addon</td>
                <td className="p-6 text-sm font-black text-amber-500 text-center bg-amber-500/5">Unlimited (∞)</td>
              </tr>
              <tr className="border-b border-slate-100/50 hover:bg-slate-50/20 transition-colors">
                <td className="p-6 text-sm font-bold text-slate-800">AI Daily Generations</td>
                <td className="p-6 text-sm font-semibold text-slate-500 text-center">3 Generations</td>
                <td className="p-6 text-sm font-semibold text-slate-500 text-center">3 Generations</td>
                <td className="p-6 text-sm font-black text-amber-500 text-center bg-amber-500/5">Unlimited (∞)</td>
              </tr>
              <tr className="border-b border-slate-100/50 hover:bg-slate-50/20 transition-colors">
                <td className="p-6 text-sm font-bold text-slate-800">Offline Downloads</td>
                <td className="p-6 text-sm font-semibold text-slate-400 text-center">—</td>
                <td className="p-6 text-sm font-semibold text-emerald-500 text-center">Yes (PDF)</td>
                <td className="p-6 text-sm font-black text-amber-500 text-center bg-amber-500/5">Interactive Maps & PDF</td>
              </tr>
              <tr className="border-b border-slate-100/50 hover:bg-slate-50/20 transition-colors">
                <td className="p-6 text-sm font-bold text-slate-800">Backpacker Circuits Support</td>
                <td className="p-6 text-sm font-semibold text-slate-500 text-center">Standard Viewing</td>
                <td className="p-6 text-sm font-semibold text-slate-500 text-center">Standard Viewing</td>
                <td className="p-6 text-sm font-black text-amber-500 text-center bg-amber-500/5">Featured Templates & Custom</td>
              </tr>
              <tr className="hover:bg-slate-50/20 transition-colors">
                <td className="p-6 text-sm font-bold text-slate-800">Customer Support Layer</td>
                <td className="p-6 text-sm font-semibold text-slate-500 text-center">Standard Web Support</td>
                <td className="p-6 text-sm font-semibold text-slate-500 text-center">Standard Web Support</td>
                <td className="p-6 text-sm font-black text-amber-500 text-center bg-amber-500/5">Priority VIP 24/7 Line</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Secured checkout & guarantees cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
        <div className="flex gap-4 p-6 bg-slate-50 rounded-2xl border border-slate-100">
          <div className="h-10 w-10 bg-white rounded-xl flex items-center justify-center shrink-0 shadow-sm border border-slate-100 text-sky-500">
            <Lock className="h-5 w-5" />
          </div>
          <div>
            <h4 className="text-sm font-black text-slate-900 uppercase tracking-wider mb-1">AES-256 Encryption</h4>
            <p className="text-xs text-slate-400 leading-normal font-semibold">Your transactions are protected by industry-standard secure socket layers and Razorpay credentials.</p>
          </div>
        </div>

        <div className="flex gap-4 p-6 bg-slate-50 rounded-2xl border border-slate-100">
          <div className="h-10 w-10 bg-white rounded-xl flex items-center justify-center shrink-0 shadow-sm border border-slate-100 text-indigo-500">
            <RefreshCw className="h-5 w-5" />
          </div>
          <div>
            <h4 className="text-sm font-black text-slate-900 uppercase tracking-wider mb-1">30-Day Money-Back Guarantee</h4>
            <p className="text-xs text-slate-400 leading-normal font-semibold">Unsatisfied with your purchase? Contact our premium helpdesk for immediate full refund processing.</p>
          </div>
        </div>

        <div className="flex gap-4 p-6 bg-slate-50 rounded-2xl border border-slate-100">
          <div className="h-10 w-10 bg-white rounded-xl flex items-center justify-center shrink-0 shadow-sm border border-slate-100 text-emerald-500">
            <ShieldCheck className="h-5 w-5" />
          </div>
          <div>
            <h4 className="text-sm font-black text-slate-900 uppercase tracking-wider mb-1">Instant Activation</h4>
            <p className="text-xs text-slate-400 leading-normal font-semibold">Verification happens in milliseconds. The premium quotas apply instantly to your dashboard.</p>
          </div>
        </div>
      </div>

      {/* Frequently Asked Questions */}
      <div className="max-w-3xl mx-auto mb-10">
        <h3 className="text-xl font-black font-heading text-center text-slate-900 mb-8">Frequently Asked Questions</h3>
        <div className="space-y-6">
          <Card className="border-none bg-slate-50 rounded-2xl p-6">
            <div className="flex gap-4">
              <HelpCircle className="h-5 w-5 text-sky-500 shrink-0 mt-0.5" />
              <div>
                <h4 className="text-sm font-black text-slate-800 mb-2">Can I purchase multiple Extra Itinerary slots?</h4>
                <p className="text-xs text-slate-400 leading-relaxed font-semibold">Yes! You can buy as many slots as you need. Each successful transaction increments your quota of active itineraries by one permanent slot.</p>
              </div>
            </div>
          </Card>

          <Card className="border-none bg-slate-50 rounded-2xl p-6">
            <div className="flex gap-4">
              <HelpCircle className="h-5 w-5 text-sky-500 shrink-0 mt-0.5" />
              <div>
                <h4 className="text-sm font-black text-slate-800 mb-2">How long is the Pro Upgrade active?</h4>
                <p className="text-xs text-slate-400 leading-relaxed font-semibold">The PRO Nomad Upgrade offered here is a Lifetime product! You pay once and enjoy absolute, unrestricted access to all current and future Travenic releases with no recurring subscriptions.</p>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </Section>
  );
}
